config/routes.rb
Rails.application.routes.draw do
  resources :restaurants

  resources :movies

  resources :confirmations

  get '/home' => 'home#index'

  root 'home#index'

  post '/restaurants/show' => 'restaurants#show'

  get '/about' => 'about#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :movie

  def self.findings(theater_address)
    gsub_theater_address = theater_address.gsub(' ','+')

    consumer_key = ENV["YELP_CONSUMER_KEY"]
    consumer_secret = ENV["YELP_CONSUMER_SECRET"]
    token = ENV["YELP_TOKEN"]
    token_secret = ENV["YELP_TOKEN_SECRET"]

    api_host = 'api.yelp.com'

    consumer = OAuth::Consumer.new(consumer_key, consumer_secret, {:site => "http://#{api_host}"})
    access_token = OAuth::AccessToken.new(consumer, token, token_secret)

    path = "/v2/search?term=restaurants&location=#{gsub_theater_address}&limit=20"

    JSON.parse(access_token.get(path).body)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    if params[:collected_info].nil?
      flash[:notice] = "You didn't select a movie! Doesn't sound like a fun date! :("
      redirect_to(:back) and return
    end
    @theater_address = params[:collected_info].split(" |; ")[1]
    @restaurants_near_theater = Restaurant.findings(@theater_address)
    @movie = params[:collected_info].split(" |; ")[0]
    @time = params[:collected_info].split(" |; ")[2]
    @theater_name = params[:collected_info].split(" |; ")[3]

  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = params[:restaurant]
    @movie = params[:movie_title]

  end


  # GET /restaurants/new
  # def new
  #   @restaurant = Restaurant.new
  # end
  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @movie = params[:movie_title]
    @address = params[:theater_address]
    @theater_name = params[:theater_name]
    @restaurants = Restaurant.findings["businesses"]

    # @restaurant = Restaurant.new(restaurant_params)
    # respond_to do |format|
    #   if @restaurant.save
    #     format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
    #     format.json { render :show, status: :created, location: @restaurant }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @restaurant.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.new(params[:theater_address])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params

    # params.require(:theater_address)
    params.require(:collected_info).permit(:theater_address, :movie_title)

  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_tag ("/confirmations"), :method => :get do %>

<table id="tableSelect" class="rowclick">
  
    <tr id="head">
      <th scope="Row">Photo</th>
      <th>Name</th>
      <th>Cuisine</th>
      <th>Rating</th>
      <th>Contact</th>
      <th>Location</th>
    </tr>
      

  <tbody>
    <% @restaurants_near_theater["businesses"].each do |restaurant|%>
    <% if restaurant["rating"] >= 3.0 %>
      <tr>
        <td id="photo-row" scope="col"><input type="radio" name="collected_info" class="restaurant-btn" value='<%="#{@movie} |; #{@theater_address} |; #{@time} |; #{restaurant["name"]} |; #{restaurant["location"]["display_address"]} |; #{@theater_name}"%>'>    <img src="<%= restaurant["image_url"]%>"></td>
        <td><%="#{restaurant["name"]}"%></td>
        <td><%cuisine = "" %><% restaurant["categories"].each do |tag|%>
                <%cuisine << "#{tag[0]}, " %>
              <%end%>
                <%= cuisine[0..-3] %></td>
        <td><%= restaurant["rating"] %></td>
        <td><%= restaurant["display_phone"] %> </td>
        <td><%= restaurant["location"]["display_address"][0] %> </td>
      </tr>
      <% end %>
      <% end %>
  </tbody>
</table>

<br>
<center><%= submit_tag 'Submit', class: 'subscribe-btn' %></center>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<!--[if !IE]><!-->
      <style>
      
      /* 
      Max width before this PARTICULAR table gets nasty
      This query will take effect for any screen smaller than 760px
      and also iPads specifically.
      */
      @media 
      only screen and (max-width: 760px),
      (min-device-width: 768px) and (max-device-width: 1024px)  {
      
            /* Force table to not be like tables anymore */
            table, thead, tbody, th, td, tr { 
                  display: block; 
            }
            
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr { 
                  position: absolute;
                  top: -9999px;
                  left: -9999px;
            }
            
            tr { border: 1px solid #ccc; text-align: left; }
            
            td { 
                  /* Behave  like a "row" */
                  border: none;
                  border-bottom: 1px solid #eee; 
                  position: relative;
                  padding-left: 50%; 
            }
            
            td:before { 
                  /* Now like a table header */
                  position: absolute;
                  /* Top/left values mimic padding */
                  top: 6px;
                  left: 6px;
                  width: 45%; 
                  padding-right: 10px; 
                  white-space: nowrap;
            }
            
            /*
            Label the data
            */
            td:nth-of-type(1):before { content: ""; }
            td:nth-of-type(2):before { content: "Name"; }
            td:nth-of-type(3):before { content: "Cuisine"; }
            td:nth-of-type(4):before { content: "Rating"; }
            td:nth-of-type(5):before { content: "Contact"; }
            td:nth-of-type(6):before { content: "Location:"; }
      }
      
      /* Smartphones (portrait and landscape) ----------- */
      @media only screen
      and (min-device-width : 320px)
      and (max-device-width : 480px) {
            body { 
                  padding: 0; 
                  margin: 0; 
                  width: 320px; }
            }
      
      /* iPads (portrait and landscape) ----------- */
      @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
            body { 
                  width: 495px; 
            }
      }
      
      </style>
      <!--<![endif]-->

<!-- Header -->
<header id="section1" class="parallax-slider">
      <!-- Navigation -->
      <div id="navigation">
            <nav class="navbar navbar-custom cl-effect-21" role="navigation">
                  <div class="container">
                        <div class="row">
                              <div class="col-md-2 mob-logo">
                                    <div class="row">
                                          <div class="site-logo">
                                                <a href="#"><%= image_tag "custom_header_logo.png" %></a>
                                          </div>
                                    </div>
                              </div>
                              

                              <div class="col-md-10 mob-menu">
                                    <div class="row">
                                          <!-- Brand and toggle get grouped for better mobile display -->
                              <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                                    <i class="fa fa-bars"></i>
                                    </button>
                              </div>
                                          <!-- Collect the nav links, forms, and other content for toggling -->
                                          <div class="collapse navbar-collapse" id="menu">
                                                <ul class="nav navbar-nav navbar-right">
                                                      <li ><a href="#">Movies</a></li>
                                                      <li class="active"><a href="#">Restaurants</a></li>
                                                      <li><a href="#">Confirmation</a></li>
                                                </ul>
                                          </div>
                                          <!-- /.Navbar-collapse -->
                                    </div>
                              </div>
                        </div>
                  </div>
                  <!-- /.container -->
            </nav>
      </div> 
      <!-- /Navigation -->                          
</header>
<!-- /Header -->


<!-- Restaurants Near -->
<div class="skills-wrap">
      <div class="container">
            <!-- Title row -->
            <div class="row">
                  <div class="col-md-12 big-title wow bounceIn">
                        <h2>Restaurants Near Your Theater:</h2>
                  </div>

                  <div class="clearfix"></div>

                  <div class="col-md-12 sub-title text-center wow slideInRight">
                        <h2>What will you have for dinner after seeing <%=@movie%>?</h2>
                  </div>
            </div>
            <!-- /Title row -->

            <!-- Restaurants Form -->
            
                  <%= render 'form' %>
            
            <!-- /Restaurants Form -->
      </div>
</div>
<!-- /Restaurants Near -->

<footer class="footer-wrap text-center">
      <div class="container">
            <p class="site-info wow fadeInUp"> 
              <div>Built with &#9829; at <a class="flatiron-link" href="http://flatironschool.com/">The Flatiron School</a> by NYC Web Development Fellows, &copy; 2014</div>
      </div>
</footer>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>